notifications:
  email: false

matrix:
  include:
  - language: go
    go: 1.10.x
    dist: xenial
    sudo: required
    services:
    - docker
    before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce lvm2 jq

script:
- .travis/unit.sh
- .travis/integration-1.sh
- .travis/integration-2.sh
- .travis/integration-3a.sh
- .travis/integration-3b.sh
- .travis/integration-4.sh
